server:
  port: 8086

spring:
  application:
    name: second-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "default"

  datasource:
    driver-class-name: org.postgresql.Driver
    password: CAS8634Sakho
    url: jdbc:postgresql://dbpostgresql:5432/microservices/second_service_bd
    username: postgres

    # JPA properties
    jpa:
      hibernate:
        ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      properties:
        hibernate:
          dialect: : org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true

topic:
  name: age-event-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhoste:8761/eureka/
    instance:
      hostname: localhost