server:
  port: 8081

spring:
  application:
    name: first-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dbpostgresql:5432/first_service_bd
    username: postgres
    password: CAS8634Sakho
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhoste:8761/eureka/

topic:
  name: personne-event-topic